#!/bin/bash
#=====================================================================
# Internatioinal SQL-Ledger-Network Association
# Copyright (c) 2014-2015
#
#  Author: Sebastian Weitmann
#     Web: http://www.sql-ledger-network.com
#   Email: info@sql-ledger-network.com
#
#  Edited: Maik Wagner (modifications to work on Ubuntu 14.04.2)
#     Web: http://www.linuxandlanguages.com
#   Email: linuxandlanguages@t-online.de
#   
#======================================================================
#
# Installation Script for SQL-Ledger Network Version (ledger123)
# including LedgerCart
# for Ubuntu 18.04 (Xenial) 
#
# Please note that Ledgercart is not working properly on Ubuntu 14.04
# yet. Some Perl code needs to be adjusted.
#======================================================================
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation version 3 of the License, or
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details:
# <http://www.gnu.org/licenses/>.
#======================================================================
#
# This script calls the installation function.
#

# Hauptinstallationsroutine / Main installation routine

installation ()
{

clear 
echo "Updating dependencies..."

cd ~/  
apt-get -y install debian-archive-keyring
add-apt-repository "deb http://archive.ubuntu.com/ubuntu $(lsb_release -sc) universe"
apt-key update 
apt-get update 
apt-get upgrade 
apt-get -y install git libcgi-simple-perl libtemplate-perl libxml-simple-perl libdate-calc-perl libgd-gd2-perl
apt-get -y install libdbd-pg-perl libdbix-simple-perl libmime-lite-perl libcgi-formbuilder-perl
apt-get -y install libpq5 postgresql postgresql-client postgresql-client-common
apt-get -y install acpid apache2 openssl ssl-cert postgresql libdbix-simple-perl libcgi-simple-perl libtext-markdown-perl libdbi-perl libdbd-pg-perl libobject-signature-perl git-core gitweb postfix mailutils texlive nano libhtml-template-perl make cpan libtemplate-perl libnumber-format-perl libuser-simple-perl lynx libcgi-formbuilder-perl libmime-lite-perl libtext-markdown-perl libdate-calc-perl libtemplate-plugin-number-format-perl libgd-gd2-perl libdatetime-perl libhtml-format-perl libmime-tools-perl apg libgd2-xpm-dev build-essential git libdbix-simple-perl
cpan DBIx::XHTML_Table
cpan GD::Thumbnail
cpan MIME::Lite::TT::HTML
a2ensite default-ssl
service apache2 reload
a2enmod ssl
a2enmod cgi
service apache2 restart
cd /var/www/html
git clone https://github.com/ledger123/ledger123.git ledger123
cd /var/www/html/ledger123
git clone git://github.com/ledger123/ledgercart.git ledgercart
mkdir spool
cd /var/www/html/ledger123/users
wget http://www.sql-ledger-network.com/debian/demo_users.tar.gz --retr-symlinks=no
tar -xvf demo_users.tar.gz
cd /var/www/html/ledger123
wget http://www.sql-ledger-network.com/debian/demo_templates.tar.gz --retr-symlinks=no
tar -xvf demo_templates.tar.gz
chown -hR www-data.www-data users templates css spool
cp sql-ledger.conf.default sql-ledger.conf
git checkout -b rel3 origin/rel3
git checkout rel3
cd ~/
wget http://www.sql-ledger-network.com/debian/sl_index.html --retr-symlinks=no
mv sl_index.html /var/www/html/index.html
wget http://www.sql-ledger-network.com/debian/sql-ledger --retr-symlinks=no
cp sql-ledger /etc/apache2/sites-available/
cd /etc/apache2/sites-enabled/
ln -s ../sites-available/sql-ledger 001-sql-ledger

echo "AddHandler cgi-script .pl" >> /etc/apache2/apache2.conf
echo "Alias /ledger123/ /var/www/html/ledger123/" >> /etc/apache2/apache2.conf
echo "<Directory /var/www/html/ledger123>" >> /etc/apache2/apache2.conf
echo "Options ExecCGI Includes FollowSymlinks" >> /etc/apache2/apache2.conf
echo "</Directory>" >> /etc/apache2/apache2.conf
echo "<Directory /var/www/html/ledger123/users>" >> /etc/apache2/apache2.conf
echo "Order Deny,Allow" >> /etc/apache2/apache2.conf
echo "Deny from All" >> /etc/apache2/apache2.conf
echo "</Directory>" >> /etc/apache2/apache2.conf



service apache2 restart
cd ~/

# Postgres Installation 
clear
echo "Initialising Postgres - Press RETURN to continue"
read confirmation
locale-gen de_DE.UTF-8
pg_createcluster --locale=de_DE.UTF-8 --encoding=UTF-8 9.3 main --start

wget http://www.sql-ledger-network.com/debian/pg_hba.conf --retr-symlinks=no
cp pg_hba.conf /etc/postgresql/9.3/main/
service postgresql restart
su postgres -c "createuser -d -S -R sql-ledger"
su postgres -c "createdb ledgercart"
su postgres -c "psql ledgercart < /var/www/html/ledger123/ledgercart/sql/ledgercart.sql"
su postgres -c "psql ledgercart < /var/www/html/ledger123/ledgercart/sql/schema.sql"
su postgres -c "psql -U postgres ledgercart < /var/www/html/ledger123/sql/Pg-custom_tables.sql"
cp /var/www/ledger123/ledgercart/config-default.pl /var/www/html/ledger123/ledgercart/config.pl

}


# Main program

clear
echo "Copyright (C) 2015  International SQL-Ledger Network Associaton"
echo "This is free software, and you are welcome to redistribute it under"
echo "certain conditions; See <http://www.gnu.org/licenses/> for more details"
echo "This program comes with ABSOLUTELY NO WARRANTY"
echo "PLEASE NOTE:"
echo "This script will make some fairly major changes to your Ubuntu system:"
echo "- Adding universe repository"
echo "- Modifying the main apache2.conf file to handle the SQL Ledger directory which will be in the default document root: /var/www/html"
echo "If you agree to these changes to your Ubuntu system please type 'installation'. Any other input will back you out and return to the command line."
read input
	
if [ "$input" = "installation" ]; then
		installation 
	     	clear
		echo 
		echo "Thank you for your patience! The automatic installation has now been completed."
		echo
		echo "You should now be able to login to the latest SQL-Ledger Network version (ledger123) as 'admin' on http://yourserver_ip/ledger123"
		echo "And don't forget to also checkout the latest version of LedgerCart on http://yourserver_ip/ledger123/ledgercart"
		echo 
		echo "Visit http://www.sql-ledger-network.com for more information on SQL-Ledger"
		echo "Visit http://forum.sql-ledger-network.com for support"
		echo "Suggestions for improvement and other feedback can be emailed to 'info@sql-ledger-network.com'. Thanks!"
		echo
		echo "IMPORTANT NOTE: This simple installation was designed to be run only on the local network."
fi
exit 0
